### PR TITLE
fix: Migrating expired data will not be retried

### LINKED ISSUE #19: 迁移已过期的数据会不断重试,导致进程一直不退出
Snipaste_2024-01-02_15-42-49

日志打印一直在retry

### PR DESCRIPTION
**Pull request by xiangyu5632**
fix #19 
solution:
1. If the returned error is `point time is expired`, no need to retry.

### CODE REVIEW

**Comment by xiangyu5632** [comment]
@shilinlee

File: src/cursor.go [hunk 1]
```diff
@@ -374,16 +375,25 @@ func (s *Scanner) writeBatches(c client.Client, cmd Migrator) error {
...
+			break
+		}
 		points := bp.Points()
 		if len(points) > 0 {
+			i++
 			logger.LogString("retry for points like:"+points[0].String(), TOLOGFILE|TOCONSOLE, LEVEL_ERROR)
 		}
+		if i == 10 {
+			break
+		}
```
Comment (shilinlee) [inline src/cursor.go]:
```suggestion
```

**Review by shilinlee — CHANGES_REQUESTED** [review]

**Review by shilinlee — APPROVED** [review]
